update cfsuki dockerfile

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -63,10 +63,45 @@ jobs:
           # https://artifacthub.io/docs/topics/repositories/container-images/
           # https://linux.die.net/man/1/date
           echo "date=$(date -u +%Y\-%m\-%d\T%H\:%M\:%S\Z)" >> $GITHUB_OUTPUT
-      - name: Install Deps
-        id: deps
+      # from: https://github.com/bootc-dev/bootc/blob/main/.github/actions/bootc-ubuntu-setup/action.yml
+      - name: Free up disk space on runner
+        shell: bash
         run: |
-          sudo apt install -y just podman
+          set -xeuo pipefail
+          sudo df -h
+          unwanted_pkgs=('^aspnetcore-.*' '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*'
+                         azure-cli google-chrome-stable firefox mono-devel)
+          unwanted_dirs=(/usr/share/dotnet /opt/ghc /usr/local/lib/android /opt/hostedtoolcache/CodeQL)
+          # Start background removal operations as systemd units; if this causes
+          # races in the future around disk space we can look at waiting for cleanup
+          # before starting further jobs, but right now we spent a lot of time waiting
+          # on the network and scripts and such below, giving these plenty of time to run.
+          n=0
+          runcleanup() {
+            sudo systemd-run -r -u action-cleanup-${n} -- "$@"
+            n=$(($n + 1))
+          }
+          runcleanup docker image prune --all --force
+          for x in ${unwanted_dirs[@]}; do
+            runcleanup rm -rf "$x"
+          done
+          # Apt removals in foreground, as we can't parallelize these
+          for x in ${unwanted_pkgs[@]}; do
+            /bin/time -f '%E %C' sudo apt-get remove -y $x
+          done
+      # We really want support for heredocs
+      - name: Update podman and install just
+        shell: bash
+        run: |
+          set -eux
+          # Require the runner is ubuntu-24.04
+          IDV=$(. /usr/lib/os-release && echo ${ID}-${VERSION_ID})
+          test "${IDV}" = "ubuntu-24.04"
+          # plucky is the next release
+          echo 'deb http://azure.archive.ubuntu.com/ubuntu plucky universe main' | sudo tee /etc/apt/sources.list.d/plucky.list
+          /bin/time -f '%E %C' sudo apt update
+          # skopeo is currently older in plucky for some reason hence --allow-downgrades
+          /bin/time -f '%E %C' sudo apt install -y --allow-downgrades crun/plucky podman/plucky skopeo/plucky just
 
       - name: Image Metadata
         uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
